spring:
  application:
    name: "KisAutoTrade"
  profiles:
    active: dev
  vprofiles:
    active: dev
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example: DEBUG  # 필요 시 패키지 별 설정

slack:
  webhookurl: ${SLACK_WEBHOOK_URL}

hantuOpenapi:
  appkey: ${DEV_HANTU_APPKEY}
  appsecret: ${DEV_HANTU_APPSECRET}
  domain: https://openapivts.koreainvestment.com:29443 #모의 도메인
  cano: ${DEV_CANO}
  acntprdtcd: ${DEV_ACNTPRDTCD}

googleSheetsapi:
  credentialsFilePath: ./googleSheetsApiServiceKey.json
  spreadsheetId: ${SPREADSHEET_ID}
  spreadsheetrange: dev_data!C3:G9