spring:
  application:
    name: "KisAutoTrade"
  profiles:
    active: ${PROFILE_ACTIVE:dev}  # 기본 실행 프로필

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example: DEBUG  # 필요 시 패키지 별 설정

slack:
  webhookurl: ${SLACK_WEBHOOK_URL}

---

spring:
  config:
    activate:
      on-profile: dev
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

hantuOpenapi:
  appkey: ${DEV_HANTU_APPKEY}
  appsecret: ${DEV_HANTU_APPSECRET}
  domain: https://openapivts.koreainvestment.com:29443 #모의 도메인
  cano: ${DEV_CANO}
  acntprdtcd: ${DEV_ACNTPRDTCD}

googleSheetsapi:
  credentialsFilePath: ./googleSheetsApiServiceKey.json
  spreadsheetId: ${SPREADSHEET_ID}
  spreadsheetrange: dev_data!C3:G9

---

spring:
  config:
    activate:
      on-profile: prod
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

hantuOpenapi:
  appkey: ${PROD_HANTU_APPKEY}
  appsecret: ${PROD_HANTU_APPSECRET}
  domain: https://openapi.koreainvestment.com:9443 #실전 도메인
  cano: ${PROD_CANO}
  acntprdtcd: ${PROD_ACNTPRDTCD}

googleSheetsapi:
  spreadsheetId: ${SPREADSHEET_ID}
  spreadsheetrange: prod_data!C3:G9