spring:
  application:
    name: "KisAutoTrade"
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example: DEBUG  # 필요 시 패키지 별 설정

vprofiles: prod

slack:
  webhookurl: ${SLACK_WEBHOOK_URL}

hantuOpenapi:
  appkey: ${PROD_HANTU_APPKEY}
  appsecret: ${PROD_HANTU_APPSECRET}
  domain: https://openapi.koreainvestment.com:9443 #실전 도메인
  cano: ${PROD_CANO}
  acntprdtcd: ${PROD_ACNTPRDTCD}

googleSheetsapi:
#  credentialsFilePath: .${CREDENTIAL_FILE_PATH}
  spreadsheetId: ${SPREADSHEET_ID}
  spreadsheetrange: prod_data!C3:G9